### ISSUE TITLE
It seems that the rouge.py code is missing, causing an error in train_detector.py.

### ISSUE THREAD

**Issue by SONOR-BE** [GreedyGeorge/COIN#2]
Traceback (most recent call last):
  File "D:\Demo\text_corrector\src_github\pycorrector\train_detector.py", line 182, in <module>
    metric = evaluate.load("./metrics/rouge")
  File "E:\software\Anaconda\envs\text_correct2\lib\site-packages\evaluate\loading.py", line 748, in load
    evaluation_module = evaluation_module_factory(
  File "E:\software\Anaconda\envs\text_correct2\lib\site-packages\evaluate\loading.py", line 686, in evaluation_module_factory
    raise FileNotFoundError(f"Couldn't find a module script at {relative_to_absolute_path(combined_path)}.")
FileNotFoundError: Couldn't find a module script at D:\Demo\text_corrector\src_github\pycorrector\metrics\rouge\rouge.py.

**Comment by macanv** [comment]
step 1:
! pip install rouge-score


step 2:
update code
metric = evaluate.load("./metric/rouge")
to
metric = evaluate.load("rouge")

**Comment by SONOR-BE** [comment]
Thank you for your answer
